# Generated by Django 4.2.27 on 2025-12-22 00:33

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Имя отправителя', max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Контактный телефон', max_length=17, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Email для связи (опционально)', max_length=254, verbose_name='Email')),
                ('message', models.TextField(help_text='Текст обращения', verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='new', help_text='Статус обработки', max_length=20, verbose_name='Статус')),
                ('is_read', models.BooleanField(default=False, help_text='Отметка о прочтении', verbose_name='Прочитано')),
                ('admin_notes', models.TextField(blank=True, help_text='Внутренние заметки', verbose_name='Заметки администратора')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='contacts_co_status_ac3bb4_idx'), models.Index(fields=['is_read', '-created_at'], name='contacts_co_is_read_c64a50_idx')],
            },
        ),
    ]
