# Generated by Django 4.2.8 on 2026-01-26 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(help_text='Контактный телефон', max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
