# Generated by Django 4.2.8 on 2026-01-26 11:32

import apps.contacts.models.contact
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(help_text='Контактный телефон (формат: +7 (999) 123-45-67)', max_length=20, validators=[apps.contacts.models.contact.validate_phone_number], verbose_name='Телефон'),
        ),
    ]
