# Generated by Django 4.2.8 on 2026-02-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, help_text='Текст обращения', null=True, verbose_name='Сообщение'),
        ),
    ]
