# Generated by Django 4.2.8 on 2026-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact_preference',
            field=models.CharField(blank=True, choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('any', 'Без разницы')], help_text='Предпочтительный способ связи: звонок, сообщение или без разницы', max_length=20, null=True, verbose_name='Способ связи'),
        ),
    ]
