# Generated by Django 4.2.27 on 2025-12-22 00:33

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Краткое название', max_length=100, verbose_name='Название услуги')),
                ('icon', models.ImageField(blank=True, help_text='Иконка услуги (рекомендуется SVG или PNG)', null=True, upload_to='services/icons/%Y/%m/', verbose_name='Иконка')),
                ('description', ckeditor.fields.RichTextField(help_text='Подробное описание услуги', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать услугу на сайте', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'name'],
            },
        ),
    ]
