# Generated by Django 4.2.27 on 2025-12-22 08:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Название для фильтра', max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, help_text='Автоматически генерируется из названия', max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в фильтрах', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать категорию на сайте', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Главное изображение для каталога', null=True, upload_to='services/images/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Начальная цена услуги', max_digits=10, null=True, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(blank=True, default='₽', help_text='Например: ₽, ₽/м², ₽/шт', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='Иконка услуги для главной страницы', null=True, upload_to='services/icons/%Y/%m/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория для фильтрации', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='Категория'),
        ),
    ]
