# Generated by Django 4.2.27 on 2025-12-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_service_image_service_price_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматически генерируется из названия', max_length=150, null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
