# Generated by Django 4.2.8 on 2026-02-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='completion_time',
            field=models.CharField(blank=True, help_text='Сроки выполнения работы (например: от 5 рабочих дней)', max_length=100, null=True, verbose_name='Сроки выполнения'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='Особенности и преимущества услуги', null=True, verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='service',
            name='materials',
            field=models.TextField(blank=True, help_text='Список используемых материалов (например: влагоустойчивый пластик, алюминиевый профиль)', null=True, verbose_name='Материалы'),
        ),
    ]
