# Generated by Django 4.2.8 on 2026-02-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_completion_time_service_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
