# Generated by Django 4.2.27 on 2025-12-22 00:33

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('title', models.CharField(default='О нас', max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(help_text='Текст о компании', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 800x600px', upload_to='about/%Y/%m/', verbose_name='Фото команды')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать блок на сайте', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('site_name', models.CharField(default='Яркий Город', max_length=100, verbose_name='Название сайта')),
                ('phone', models.CharField(help_text='Формат: +7(999)999-99-99', max_length=17, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Контактный email', max_length=254, verbose_name='Email')),
                ('address', models.CharField(help_text='Физический адрес офиса', max_length=300, verbose_name='Адрес')),
                ('working_hours', models.CharField(default='Мы открыты с 10:00 до 19:00', max_length=100, verbose_name='Часы работы')),
                ('vk_link', models.URLField(blank=True, help_text='Ссылка на VK', verbose_name='VK')),
                ('instagram_link', models.URLField(blank=True, help_text='Ссылка на Instagram', verbose_name='Instagram')),
                ('telegram_link', models.URLField(blank=True, help_text='Ссылка на Telegram', verbose_name='Telegram')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать эти настройки', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('title', models.CharField(help_text='Основной заголовок слайда', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, help_text='Описание под заголовком', max_length=300, verbose_name='Подзаголовок')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1920x800px', upload_to='slider/%Y/%m/', verbose_name='Изображение')),
                ('button_text', models.CharField(blank=True, default='Наши услуги', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, default='#services', max_length=200, verbose_name='Ссылка кнопки')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения слайда', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать слайд на сайте', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
