# Generated by Django 4.2.27 on 2025-12-22 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='ФИО клиента', max_length=100, verbose_name='Имя клиента')),
                ('position', models.CharField(blank=True, help_text='Должность и компания', max_length=200, verbose_name='Должность')),
                ('avatar', models.ImageField(blank=True, help_text='Фото клиента', null=True, upload_to='testimonials/%Y/%m/', verbose_name='Фото')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Оценка от 1 до 5', verbose_name='Рейтинг')),
                ('text', models.TextField(help_text='Содержание отзыва', verbose_name='Текст отзыва')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать на сайте', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
