# Generated by Django 4.2.8 on 2026-01-26 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('chat_id', models.BigIntegerField(help_text='ID чата в Telegram', unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, help_text='Имя пользователя в Telegram', max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя', max_length=100, null=True, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, help_text='Получать уведомления', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Telegram чат',
                'verbose_name_plural': 'Telegram чаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Токен Telegram бота для уведомлений', max_length=200, verbose_name='Telegram Bot Token'),
        ),
    ]
