# Generated by Django 4.2.8 on 2026-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_telegramchat_sitesettings_telegram_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Подзаголовок под основным заголовком (например: Делаем ваш бизнес заметным в Петрозаводске)', max_length=300, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='О нас', help_text='Основной заголовок (например: Яркий город)', max_length=200, verbose_name='Заголовок'),
        ),
    ]
