# Generated by Django 4.2.8 on 2026-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutus_paragraph_margin_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title_margin_bottom',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Расстояние между заголовком и подзаголовком (в rem, например: 1.0, 1.5, 2.0)', max_digits=4, verbose_name='Отступ под заголовком (rem)'),
        ),
    ]
