# Generated by Django 4.2.8 on 2026-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutus_title_margin_bottom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='title_margin_bottom',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle_margin_bottom',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Расстояние между подзаголовком и текстом (в rem, например: 0.5, 1.0, 1.5)', max_digits=4, verbose_name='Отступ под подзаголовком (rem)'),
        ),
    ]
