# Generated by Django 4.2.8 on 2026-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_aboutus_title_margin_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='paragraph_margin_bottom',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Расстояние между абзацами текста (в rem, например: 0.5, 0.75, 1.0). Используйте точку (.) в качестве разделителя.', max_digits=4, verbose_name='Отступ между абзацами (rem)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle_margin_bottom',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Расстояние между подзаголовком и текстом (в rem, например: 0.5, 1.0, 1.5). Используйте точку (.) в качестве разделителя.', max_digits=4, verbose_name='Отступ под подзаголовком (rem)'),
        ),
    ]
