# Generated by Django 4.2.8 on 2026-02-05 10:23

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_aboutus_paragraph_margin_bottom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('icon_class', models.CharField(default='bi-check-circle-fill', help_text='CSS класс иконки из Bootstrap Icons (например: bi-check-circle-fill)', max_length=100, verbose_name='Класс иконки')),
                ('number', models.IntegerField(help_text='Числовое значение статистики', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Число')),
                ('suffix', models.CharField(blank=True, default='', help_text='Текст после числа (например: "+", "%", "м²")', max_length=10, verbose_name='Суффикс')),
                ('label', models.CharField(help_text='Текст под числом (например: "Проектов реализовано")', max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше = выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать статистику на сайте', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
