# Generated by Django 4.2.8 on 2026-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='badge_position',
            field=models.CharField(choices=[('right', 'Справа'), ('center', 'По центру'), ('left', 'Слева')], default='center', help_text='Горизонтальное выравнивание бейджа на фото', max_length=20, verbose_name='Позиция бейджа'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='show_badge',
            field=models.BooleanField(default=True, help_text='Если выключено, жёлтый кружок на фото не отображается', verbose_name='Показывать бейдж «лет опыта»'),
        ),
    ]
