# Generated by Django 4.2.8 on 2026-02-13 11:32

from django.db import migrations, models


def set_badge_position_right(apps, schema_editor):
    AboutUs = apps.get_model('main', 'AboutUs')
    AboutUs.objects.all().update(badge_position='right')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_add_about_badge_settings'),
    ]

    operations = [
        migrations.RunPython(set_badge_position_right, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aboutus',
            name='badge_position',
            field=models.CharField(choices=[('right', 'Справа'), ('center', 'По центру'), ('left', 'Слева')], default='right', help_text='Горизонтальное выравнивание бейджа на фото', max_length=20, verbose_name='Позиция бейджа'),
        ),
    ]
