# Generated by Django 4.2.8 on 2026-02-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_badge_position_default_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_link',
            field=models.URLField(blank=True, help_text='Ссылка на соцсеть Макс', verbose_name='Макс (MAX)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_instagram',
            field=models.BooleanField(default=True, help_text='Отображать ссылку на Instagram в футере', verbose_name='Показывать Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_max',
            field=models.BooleanField(default=True, help_text='Отображать ссылку на Макс в футере', verbose_name='Показывать Макс'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_telegram',
            field=models.BooleanField(default=True, help_text='Отображать ссылку на Telegram в футере', verbose_name='Показывать Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_vk',
            field=models.BooleanField(default=True, help_text='Отображать ссылку на VK в футере', verbose_name='Показывать VK'),
        ),
    ]
