# Generated by Django 4.2.27 on 2025-12-22 00:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Используется в URL', max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать категорию на сайте', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('title', models.CharField(help_text='Название проекта', max_length=200, verbose_name='Название работы')),
                ('description', ckeditor.fields.RichTextField(help_text='Подробное описание проекта', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Главное изображение работы (рекомендуется 800x600px)', upload_to='portfolio/%Y/%m/', verbose_name='Изображение')),
                ('client', models.CharField(blank=True, help_text='Название клиента', max_length=200, verbose_name='Клиент')),
                ('date_completed', models.DateField(blank=True, help_text='Когда был завершен проект', null=True, verbose_name='Дата завершения')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать на главной странице', verbose_name='На главной')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать работу на сайте', verbose_name='Активна')),
                ('category', models.ForeignKey(help_text='Категория работы', on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_items', to='portfolio.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['-date_completed', '-created_at'],
            },
        ),
    ]
