# Generated by Django 4.2.27 on 2025-12-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slug'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Связанная услуга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_works', to='services.service', verbose_name='Услуга'),
        ),
    ]
