# Generated by Django 4.2.27 on 2025-12-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slug'),
        ('portfolio', '0002_portfolioitem_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(help_text='Категория работы (из услуг)', on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_items', to='services.servicecategory', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
