# Generated by Django 4.2.8 on 2026-02-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioitem_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
    ]
