# Generated by Django 4.2.8 on 2026-02-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolioitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', '-date_completed', '-created_at'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке. Можно менять в списке работ в админке.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показывать в блоке из 4 работ на главной странице (в своей категории). Сначала выводятся работы с этой галочкой.', verbose_name='На главной'),
        ),
    ]
